ddf<-read.table('../exdata-data-household_power_consumption//household_power_consumption.txt',sep=';',nrows=2075259,header = T)
ddf$Date<-as.Date(ddf$Date,format="%d/%m/%Y")
dd<-subset(ddf,Date=="2007-02-01" | Date=="2007-02-02")
dd$Time<-paste(as.character(dd$Date),as.character(dd$Time),sep=",")
dd$Time<-strptime(dd$Time,format="%Y-%m-%d,%H:%M:%S")
dd$Day<-weekdays(dd$Date)
dd$Sub_metering_1<-as.numeric(as.character(dd$Sub_metering_1))
dd$Sub_metering_2<-as.numeric(as.character(dd$Sub_metering_2))
dd$Sub_metering_3<-as.numeric(as.character(dd$Sub_metering_3))
png(file="plot3.png",height=480,width=480)
par(mfrow = c(1,1))
with(dd,plot(Time,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
with(dd,points(Time,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering"))
with(dd,points(Time,Sub_metering_2,type="l",col="red",xlab="",ylab="Energy sub metering"))
with(dd,points(Time,Sub_metering_3,type="l",col="blue",xlab="",ylab="Energy sub metering"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()