ddf<-read.table('../exdata-data-household_power_consumption//household_power_consumption.txt',sep=';',nrows=2075259,header = T)
ddf$Date<-as.Date(ddf$Date,format="%d/%m/%Y")
dd<-subset(ddf,Date=="2007-02-01" | Date=="2007-02-02")
dd$Time<-paste(as.character(dd$Date),as.character(dd$Time),sep=",")
dd$Time<-strptime(dd$Time,format="%Y-%m-%d,%H:%M:%S")
dd$Day<-weekdays(dd$Date)
dd$Global_active_power<-as.numeric(as.character(dd$Global_active_power))
par(mfrow = c(1,1))
with(dd,plot(Time,Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)"))
dev.copy(png,file="plot2.png",height=480,width=480)
dev.off()